{{/*
See chart value file for details of the logic used to generate this setting value below.!!!
*/}}
{{- $includeInitialJobs := (ne (.Values.includeInitialJobs | typeOf) "<nil>") | ternary .Values.includeInitialJobs ( (ne (.Values.global.connectors.includeInitialJobs | typeOf) "<nil>") | ternary .Values.global.connectors.includeInitialJobs .Values.defaultSettings.includeInitialJobs) -}}
{{- if $includeInitialJobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: connector-{{ .Values.config.id }}
spec:
  template:
    metadata:
      name: connector-{{ .Values.config.id }}
    spec:
      {{- include "magda.imagePullSecrets" . | indent 6 }}
      containers:
        - name: connector-{{ .Values.config.id }}
          image: {{ include "magda.image" . | quote }}
          imagePullPolicy: {{ include "magda.imagePullPolicy" . | quote }}
          command:
            - "node"
            - "/usr/src/app/component/dist/index.js"
            - "--tenantId"
            - {{ .Values.config.tenantId | default .Values.defaultTenantId | quote }}
            - "--config"
            - "/etc/config/config.json"
            - "--registryUrl"
            - "http://registry-api/v0"
          resources: 
{{ .Values.resources | toYaml | indent 12 }}
          volumeMounts:
            - mountPath: /etc/config
              name: config
          env:
            - name: USER_ID
              value: 00000000-0000-4000-8000-000000000000
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt-secret
      restartPolicy: "OnFailure"
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}-{{ .Values.config.id }}
            items:
              - key: config.json
                path: config.json
{{- end }}