name: Main CI Workflow

on: push

env:
  REPO_NAME: magda-project-open-data-connector

jobs:
  build-test-docker:
    name: Build, Test & Push to Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build
      - run: yarn test

      - name: helm-build-dependencies
        run: helm dep up deploy/${REPO_NAME}

      - run: yarn helm-lint

      - name: Login to GitHub Package Repository
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image & Push to Github Container Registry
        run: yarn docker-build-prod --repository=ghcr.io/${{ github.repository_owner }} --name=${REPO_NAME} --version=${GITHUB_SHA} --platform=linux/amd64,linux/arm64
