name: CI Release Helm Chart

on:
  release:
    types: [published]

env:
  # [avoid issue when Github action upgraded from 18.04 default to 20.04](https://github.com/aws/aws-cli/issues/5262)
  AWS_EC2_METADATA_DISABLED: true
  REPO_NAME: magda-project-open-data-connector
  # Github account username (used for access github registry)
  GH_USERNAME: magdabot
  # Github Orgnisation name or user name for this repo
  GH_ORGNAME: magda-io
  #Docker Hub username
  DH_USERNAME: magdabot
  #S3 bucket name: this s3 bucket will be used to store published helm chart and index
  S3_BUCKET: magda-charts

jobs:
  release-helm-chart:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
      - run: yarn test

      - name: helm-build-dependencies
        run: helm dep up deploy/${REPO_NAME}

      - name: helm-check
        run: yarn helm-lint

      - name: helm-chart-version-check
        run: yarn check-helm-chart-version deploy/${REPO_NAME}/Chart.yaml

      - name: Login to GitHub Package Repository
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image & Push to Github Container Registry
        run: yarn docker-build-prod --repository=ghcr.io/${{ github.repository_owner }} --name=${REPO_NAME} --version=${GITHUB_SHA} --platform=linux/amd64,linux/arm64

      - name: Login to Docker Hub
        env:
          DH_TOKEN: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: docker login -u ${DH_USERNAME} -p ${DH_TOKEN}

      - name: Re-tag & Push Docker Image to Docker Hub
        run: |
          PACKAGE_JSON_VERSION=$(jq -r ".version" package.json)
          docker container run --rm --net host \
            -v regctl-conf:/home/appuser/.regctl/ \
            -v $HOME/.docker/config.json:/home/appuser/.docker/config.json \
            regclient/regctl:latest image copy ghcr.io/${{ github.repository_owner }}/${REPO_NAME}:${GITHUB_SHA} docker.io/data61/${REPO_NAME}:${PACKAGE_JSON_VERSION}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release Helm Chart
        env:
          CR_TOKEN: "${{ secrets.GH_ACCESS_TOKEN }}"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd deploy
          mkdir -p sync_dir
          mkdir -p index_dir
          if ! aws s3 cp s3://${S3_BUCKET}/index.yaml index_dir/index.yaml; then echo "failed to copy current repo index" && exit 1; fi
          helm package -d sync_dir ${REPO_NAME}
          helm repo index --merge "index_dir/index.yaml" sync_dir
          mv -f sync_dir/index.yaml index_dir/index.yaml
          aws s3 sync sync_dir s3://${S3_BUCKET}/
          aws s3 cp index_dir/index.yaml s3://${S3_BUCKET}/index.yaml
